# Generated by Django 5.2.16 on 2026-07-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_calorie_goal',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
