# Generated by Django 5.2.16 on 2026-07-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_daily_calorie_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_consent',
            field=models.BooleanField(default=False),
        ),
    ]
