# Generated by Django 5.2.16 on 2026-07-20 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('IFCT', 'Ifct'), ('USDA', 'Usda')], max_length=4)),
                ('source_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('food_group', models.CharField(max_length=64)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id'), name='uq_food_source')],
            },
        ),
        migrations.CreateModel(
            name='VisionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, unique=True)),
                ('match_quality', models.CharField(choices=[('exact', 'Exact'), ('proxy', 'Proxy')], default='exact', max_length=8)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vision_classes', to='nutrition.food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_100g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='nutrition.food')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.nutrient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('food', 'nutrient'), name='uq_food_nutrient')],
            },
        ),
        migrations.CreateModel(
            name='PortionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=32)),
                ('grams', models.DecimalField(decimal_places=1, max_digits=7)),
                ('is_default', models.BooleanField(default=False)),
                ('vision_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='nutrition.visionclass')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vision_class', 'unit'), name='uq_portion')],
            },
        ),
    ]
