# Generated by Django 5.2.16 on 2026-07-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='carbs_g',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='meallog',
            name='fat_g',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='meallog',
            name='protein_g',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
