# Generated by Django 5.2.16 on 2026-07-22 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_meallog_carbs_g_meallog_fat_g_meallog_protein_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='carbs_g',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='fat_g',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='protein_g',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
